return {
	Janitor = {URL = "https://raw.githubusercontent.com/RoStrap/Events/master/Janitor.lua"};
	Signal = {URL = "https://raw.githubusercontent.com/RoStrap/Events/master/Signal.lua"};
	Keys = {URL = "https://raw.githubusercontent.com/RoStrap/Input/master/Keys.lua"};
	Enumeration = {URL = "https://raw.githubusercontent.com/RoStrap/Classes/master/Enumeration.lua"};
	PseudoInstance = {URL = "https://raw.githubusercontent.com/RoStrap/Classes/master/PseudoInstance.lua"};
	ReplicatedPseudoInstance = {URL = "https://raw.githubusercontent.com/RoStrap/Classes/master/ReplicatedPseudoInstance.lua"};
	Sentry = {URL = "https://github.com/RoStrap/Sentry"};
	Bezier = {URL = "https://raw.githubusercontent.com/RoStrap/Interpolation/master/Bezier.lua"};
	EasingFunctions = {URL = "https://raw.githubusercontent.com/RoStrap/Interpolation/master/EasingFunctions.lua"};
	Lerps = {URL = "https://raw.githubusercontent.com/RoStrap/Interpolation/master/Lerps.lua"};
	Tween = {URL = "https://raw.githubusercontent.com/RoStrap/Interpolation/master/Tween.lua"};
	Array = {URL = "https://raw.githubusercontent.com/RoStrap/DataTypes/master/Array.lua"};
	HTMLParser = {URL = "https://raw.githubusercontent.com/RoStrap/DataTypes/master/HTMLParser.lua"};
	SortedArray = {URL = "https://raw.githubusercontent.com/RoStrap/DataTypes/master/SortedArray.lua"};
	Table = {URL = "https://raw.githubusercontent.com/RoStrap/DataTypes/master/Table.lua"};
	Leveler = {URL = "https://raw.githubusercontent.com/RoStrap/Math/master/Leveler.module.lua"};
	Normal = {URL = "https://raw.githubusercontent.com/RoStrap/Math/master/Normal.module.lua"};
	WeightedProbabilityFunction = {URL = "https://raw.githubusercontent.com/RoStrap/Math/master/WeightedProbabilityFunction.module.lua"};
	FastSpawn = {URL = "https://raw.githubusercontent.com/RoStrap/Helper/master/FastSpawn.module.lua"};
	Make = {URL = "https://raw.githubusercontent.com/RoStrap/Helper/master/Make.module.lua"};
	Date = {URL = "https://raw.githubusercontent.com/RoStrap/Time/master/Date.lua"};
	SyncedPoller = {URL = "https://raw.githubusercontent.com/RoStrap/Time/master/SyncedPoller.lua"};
	Debug = {URL = "https://raw.githubusercontent.com/RoStrap/Debugging/master/Debug.module.lua"};
	Typer = {URL = "https://raw.githubusercontent.com/RoStrap/Debugging/master/Typer.lua"};
	AsymmetricTransformation = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/AsymmetricTransformation.lua"};
	Checkbox = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/Checkbox.lua"};
	ChoiceDialog = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/ChoiceDialog.lua"};
	Color = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/Color.lua"};
	Radio = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/Radio.lua"};
	RadioGroup = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/RadioGroup.lua"};
	RippleButton = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/RippleButton.lua"};
	Rippler = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/Rippler.lua"};
	SelectionController = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/SelectionController.lua"};
	Shadow = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/Shadow.lua"};
	Snackbar = {URL = "https://raw.githubusercontent.com/RoStrap/RoStrapUI/master/Snackbar.lua"};

	Try = {
		URL = "Validark/RBX-Try-Library/tree/patch-4";
		Description = "An asynchronous pcall-wrapper for interdependent error-prone functions";
	};

	EvLightning = {
		URL = "evaera/EvLightning";
		Description = "Realistic-looking lightning bolt generator";
		Documentation = "https://github.com/evaera/EvLightning/blob/master/README.md";
	};

	RadialImage = {
		URL = "evaera/RadialSpriteSheetGenerator/blob/master/roblox/RadialImage.lua";
		Description = "A library which displays radial progress indicators using a sprite sheet generated by a nifty tool";
		Documentation = "https://github.com/evaera/RadialSpriteSheetGenerator/blob/master/README.md";
	};

	Ready = {
		URL = "EmeraldSlash/RbxReady/blob/master/Ready.lua";
		Description = "A Library for yielding until an object's descendants have finished replicating";
		Documentation = "https://github.com/EmeraldSlash/RbxReady/blob/master/README.md";
	};

	DataStoreService = {
		URL = "buildthomas/MockDataStoreService/tree/master/lib";
		Description = "An implementation of DataStoreService in Lua for use in Studio";
		Documentation = "https://github.com/buildthomas/MockDataStoreService/blob/master/README.md";
	};

	Promise = {
		URL = "LPGhatguy/roblox-lua-promise/tree/master/lib";
		Description = "An implementation of Promise similar to Promise/A+";
		Documentation = "https://github.com/LPGhatguy/roblox-lua-promise/blob/master/README.md";
	};

	Cmdr = {
		URL = "evaera/Cmdr";
		Description = "A fully extensible and type-safe admin-commands console";
		Documentation = "https://github.com/evaera/Cmdr/blob/master/README.md";
		ParentFolderPath = "Cmdr.Server"; -- Dot separated directory within Repository.Packages into which Cmdr will be installed
	};
};
