return {
	RoStrap = {
		URL = "RoStrap"; -- Import everything under the organization `RoStrap`
	};

	Try = {
		URL = "Validark/RBX-Try-Library/tree/patch-4";
		Description = "An asynchronous pcall-wrapper for interdependent error-prone functions";
	};

	EvLightning = {
		URL = "evaera/EvLightning";
		Description = "Realistic-looking lightning bolt generator";
		Documentation = "https://github.com/evaera/EvLightning/blob/master/README.md";
	};
	
	RadialImage = {
		URL = "evaera/RadialSpriteSheetGenerator/blob/master/roblox/RadialImage.lua";
		Description = "A library which displays radial progress indicators using a sprite sheet generated by a nifty tool";
		Documentation = "https://github.com/evaera/RadialSpriteSheetGenerator/blob/master/README.md";
	};
	
	Ready = {
		URL = "EmeraldSlash/RbxReady/blob/master/Ready.lua";
		Description = "A Library for yielding until an object's descendants have finished replicating";
		Documentation = "https://github.com/EmeraldSlash/RbxReady/blob/master/README.md";
	};
	
	DataStoreService = {
		URL = "buildthomas/MockDataStoreService/tree/master/lib";
		Description = "An implementation of DataStoreService in Lua for use in Studio";
		Documentation = "https://github.com/buildthomas/MockDataStoreService/blob/master/README.md";
	};
};
