return {
	RoStrap = {
		URL = "RoStrap"; -- Import everything under the organization `RoStrap`
	};

	Try = {
		URL = "Validark/RBX-Try-Library/tree/patch-4";
		Description = "An asynchronous pcall-wrapper for interdependent error-prone functions";
	};

	EvLightning = {
		URL = "evaera/EvLightning";
		Description = "Realistic-looking lightning bolt generator";
		Documentation = "https://github.com/evaera/EvLightning/blob/master/README.md";
	};
	
	RadialImage = {
		URL = "evaera/RadialSpriteSheetGenerator/blob/master/roblox/RadialImage.lua";
		Description = "A library which displays radial progress indicators using a sprite sheet generated by a nifty tool";
		Documentation = "https://github.com/evaera/RadialSpriteSheetGenerator/blob/master/README.md";
	};
	
	Ready = {
		URL = "EmeraldSlash/RbxReady/blob/master/Ready.lua";
		Description = "A Library for yielding until an object's descendants have finished replicating";
		Documentation = "https://github.com/EmeraldSlash/RbxReady/blob/master/README.md";
	};
  
 	PseudoMouse = {
		URL = "EmeraldSlash/RbxMouse/blob/master/RbxMouse.lua";
		Description = "A clean mouse library using up-to-date input APIs";
		Documentation = "https://github.com/EmeraldSlash/RbxMouse/blob/master/README.md";
	};
	
	DataStoreService = {
		URL = "buildthomas/MockDataStoreService/tree/master/lib";
		Description = "An implementation of DataStoreService in Lua for use in Studio";
		Documentation = "https://github.com/buildthomas/MockDataStoreService/blob/master/README.md";
	};
	
	Promise = {
		URL = "LPGhatguy/roblox-lua-promise/tree/master/lib";
		Description = "An implementation of Promise similar to Promise/A+";
		Documentation = "https://github.com/LPGhatguy/roblox-lua-promise/blob/master/README.md";
	};
	
	Cmdr = {
		URL = "evaera/Cmdr";
		Description = "A fully extensible and type-safe admin-commands console";
		Documentation = "https://github.com/evaera/Cmdr/blob/master/README.md";
		ParentFolderPath = "Cmdr.Server"; -- Dot separated directory within Repository.Packages into which Cmdr will be installed
	};
};
